export const staticTrendingMovies = [
  {
    id: "static-1",
    name: "Dune: Part Two",
    description: "Pol Atreydes Çani və Fremenlərlə güclərini birləşdirərək ailəsini məhv edən sui-qəsdçilərdən qisas almaq üçün yola çıxır. O, həyatının sevgisi ilə kainatın taleyi arasında seçim etməli olur.",
    country: "ABŞ",
    director: "Denis Villeneuve",
    actors: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    genres: [{ id: "1", title: "Elmi-Fantastika" }, { id: "2", title: "Döyüş" }],
    duration: 166,
    year: 2024,
    ageLimit: "SIXTEEN",
    languages: ["EN", "AZ"],
    image: "https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg",
    rating: 8.6,
    youtubeUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    imdbLink: "https://www.imdb.com/title/tt15239678/"
  },
  {
    id: "static-2",
    name: "Oppenheimer",
    description: "İkinci Dünya Müharibəsi zamanı fizik Robert Oppenheimerin rəhbərliyi altında ilk atom bombasının hazırlanması prosesi və sonradan onun qarşılaşdığı siyasi təzyiqlər.",
    country: "ABŞ",
    director: "Christopher Nolan",
    actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    genres: [{ id: "3", title: "Dram" }, { id: "4", title: "Bioqrafiya" }],
    duration: 180,
    year: 2023,
    ageLimit: "SIXTEEN",
    languages: ["EN", "RU"],
    image: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
    rating: 8.4,
    youtubeUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    imdbLink: "https://www.imdb.com/title/tt15398776/"
  },
  {
    id: "static-3",
    name: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales Bruklinin tam ştatlı hörümçək adamı olaraq geri dönür. O, multikainat boyu səyahət edərək digər Hörümçək-İnsanlar komandası ilə birlikdə yeni təhlükəyə qarşı mübarizə aparır.",
    country: "ABŞ",
    director: "Joaquim Dos Santos",
    actors: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    genres: [{ id: "5", title: "Animasiya" }, { id: "2", title: "Döyüş" }],
    duration: 140,
    year: 2023,
    ageLimit: "SIX",
    languages: ["EN", "AZ", "TR"],
    image: "https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg",
    rating: 8.7,
    youtubeUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    imdbLink: "https://www.imdb.com/title/tt9362722/"
  },
  {
    id: "static-4",
    name: "Interstellar",
    description: "Bəşəriyyətin son günlərində bir qrup tədqiqatçı insan irqinin sağ qalmasını təmin etmək üçün kosmosda yeni yaşayış yararlı planet tapmaq məqsədilə solucan dəliyindən keçir.",
    country: "ABŞ",
    director: "Christopher Nolan",
    actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    genres: [{ id: "1", title: "Elmi-Fantastika" }, { id: "3", title: "Dram" }],
    duration: 169,
    year: 2014,
    ageLimit: "SIX",
    languages: ["EN", "RU"],
    image: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    rating: 8.7,
    youtubeUrl: "https://www.youtube.com/watch?v=zSWdZAToEsQ",
    imdbLink: "https://www.imdb.com/title/tt0816692/"
  }
];
